import type { LogEvent } from "./types";

export const mockLogEvents: LogEvent[] = [
  {
    id: "ev-001",
    createdAt: "2026-02-08T14:32:00.000Z",
    severity: "info",
    category: "auth",
    action: "LOGIN_SUCCESS",
    message: "Kullanıcı başarıyla giriş yaptı",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "session" },
    status: "success",
    metadata: { method: "password" },
    request: { ip: "192.168.1.10", userAgent: "Mozilla/5.0..." },
  },
  {
    id: "ev-002",
    createdAt: "2026-02-08T14:28:00.000Z",
    severity: "info",
    category: "releases",
    action: "RELEASE_CREATED",
    message: "Yeni sürüm oluşturuldu",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "release", id: "rel-42" },
    status: "success",
    metadata: { version: "1.2.0" },
  },
  {
    id: "ev-003",
    createdAt: "2026-02-08T14:15:00.000Z",
    severity: "warning",
    category: "releases",
    action: "RELEASE_STATUS_CHANGED",
    message: "Sürüm durumu güncellendi",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "release", id: "rel-41" },
    status: "success",
    metadata: { from: "draft", to: "deployed" },
  },
  {
    id: "ev-004",
    createdAt: "2026-02-08T13:45:00.000Z",
    severity: "info",
    category: "auth",
    action: "LOGIN_SUCCESS",
    message: "Kullanıcı giriş yaptı",
    actor: { id: "u-2", email: "selcuk@genericmusic.net", role: "admin" },
    target: { entity: "session" },
    status: "success",
    request: { ip: "10.0.0.5", userAgent: "Chrome/120..." },
  },
  {
    id: "ev-005",
    createdAt: "2026-02-08T13:00:00.000Z",
    severity: "info",
    category: "settings",
    action: "SYSTEM_SETTINGS_UPDATED",
    message: "Sistem ayarları güncellendi",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "system_settings", id: "1" },
    status: "success",
    metadata: { changed: ["mail_enabled"] },
  },
  {
    id: "ev-006",
    createdAt: "2026-02-08T12:30:00.000Z",
    severity: "error",
    category: "auth",
    action: "LOGIN_FAILED",
    message: "Başarısız giriş denemesi",
    actor: { email: "unknown@test.com" },
    target: { entity: "session" },
    status: "failure",
    metadata: { reason: "invalid_credentials" },
    request: { ip: "203.0.113.1", userAgent: "curl/7.68" },
  },
  {
    id: "ev-007",
    createdAt: "2026-02-08T12:00:00.000Z",
    severity: "info",
    category: "roles",
    action: "ROLE_ASSIGNED",
    message: "Rol ataması yapıldı",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "profile", id: "u-3" },
    status: "success",
    metadata: { role: "admin" },
  },
  {
    id: "ev-008",
    createdAt: "2026-02-08T11:45:00.000Z",
    severity: "critical",
    category: "security",
    action: "RATE_LIMIT_EXCEEDED",
    message: "API rate limit aşıldı",
    actor: { id: "u-4", email: "abuse@example.com" },
    target: { entity: "api" },
    status: "failure",
    metadata: { endpoint: "/api/version/releases", limit: 100 },
    request: { ip: "198.51.100.1", userAgent: "Python/3.11" },
  },
  {
    id: "ev-009",
    createdAt: "2026-02-08T11:20:00.000Z",
    severity: "info",
    category: "db",
    action: "MIGRATION_APPLIED",
    message: "Veritabanı migrasyonu uygulandı",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "migration", id: "20260208000000" },
    status: "success",
    metadata: { name: "add_audit_fields" },
  },
  {
    id: "ev-010",
    createdAt: "2026-02-08T10:55:00.000Z",
    severity: "info",
    category: "import_export",
    action: "EXPORT_STARTED",
    message: "Dışa aktarma başlatıldı",
    actor: { id: "u-1", email: "info@genericmusic.net", role: "system_owner" },
    target: { entity: "export", id: "exp-12" },
    status: "success",
    metadata: { dataset: "etkinlikler", format: "csv" },
  },
  {
    id: "ev-011",
    createdAt: "2026-02-08T10:30:00.000Z",
    severity: "warning",
    category: "system",
    action: "DISK_USAGE_HIGH",
    message: "Disk kullanımı yüksek",
    actor: {},
    target: { entity: "system" },
    status: "success",
    metadata: { usagePercent: 85 },
  },
  {
    id: "ev-012",
    createdAt: "2026-02-08T10:00:00.000Z",
    severity: "info",
    category: "auth",
    action: "LOGOUT",
    message: "Kullanıcı çıkış yaptı",
    actor: { id: "u-2", email: "selcuk@genericmusic.net", role: "admin" },
    target: { entity: "session" },
    status: "success",
  },
];
